# Generated by Django 6.1.2 on 2026-10-08 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время приема')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='planned', max_length=20, verbose_name='Статус приема')),
                ('medical_conclusion', models.TextField(blank=True, null=True, verbose_name='Медицинское заключение / Рекомендации')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='appointment_results/', verbose_name='Файл с результатами диагностики (PDF / Изображение)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.doctor', verbose_name='Врач')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.medicalservice', verbose_name='Медицинская услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на приемы',
                'ordering': ['-date_time'],
            },
        ),
    ]
